version: '3'

services:
  postgres:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_mars
    networks:
      - mars-network

  sqs:
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./sqs/elasticmq.conf:/etc/elasticmq/elasticmq.conf
    networks:
      - mars-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9001:9000'
    volumes:
      - ./src:/var/www
    #    command: chmod -R 777 /var/www/storage
    depends_on:
      - postgres
    networks:
      - mars-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - postgres
    networks:
      - mars-network

networks:
  mars-network:
